language: node_js
node_js:
  - "10.23.0"
before_install:
- sudo apt-get -y install libgconf-2-4
cache:
  directories:
    - "node_modules"
addons:
  apt:
    update: true
  sonarcloud:
    organization: damoresa-github
    token:
      secure: XrjC6fk+6D9Ew6e/PrQXSm3LiQS4G7H7o6vkjB4KPIA9X+idyIGvfsHg+/EhAmIi6/96PtLKscWCpE675RmQ8HS4/B+mANSW45/wycAEat53vhn95LBCT1pXt/3hDkdFaV597jUZnRGzoB34oA114Ury0rdmgy7rQVFJWNUrcMixqqmphNj5TOM3F+49fasgEX60uCKjE7MRH9pLOL5taAUr/SyHE5AveSwckrN0dOJ8efkL/91OglKbvCPICW2EDGeQTiRdAcQrfrKjiSsh45+SnZVSV11TKE+BDp0sgY/U9yFYR7n2VCl27i9GBZ10iXQqe3K2c5CLcw2pj8JapyNxORZrBgt7P8QABOsS3w8wzH67zDtJlYJvWZAUd/WktFijQCW3ddYuwXi7+zOBy6Rp47dv6T19E20MeQbfdagINorYbT18gqKBD+Hd8lVY5JpliVGOk6JEkmd61dCuaEO2Nhr0Lz1//RxZhrvxgKrtPRdQWs6ZOzFMjzyS5RSvjQHtJPz9ZjXRJ1ThvE0GVFfJk4AMblzd6BXqnoLs7LHD/jfFDe7PKs//fFzuDT1C6wQDBfd/fla/zIFySrhwvfwD2cWY2wz37eeRw9X/a9VmTxQMTt+73aR3dECMmPhRdMUsMaVhht+PCjWKiuPqXELChDIASr7QwE9Yj0XAums=
script:
- npm run build:production:aot
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- sonar-scanner
deploy:
  provider: surge
  project: ./dist/
  domain: ng-taskmanager.surge.sh
