language: node_js
node_js:
  - "8.9.1"
cache:
  directories:
    - "node_modules"
script: npm run build:production:aot && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: surge
  project: ./dist/
  domain: ng-taskmanager.surge.sh
  skip_cleanup: true